BACKUP_DIR="$HOME/backups"
LOG_FILE="$SCRIPT_DIR/../logs/app.log"
DOT_FOLDER="$(cd "$SCRIPT_DIR/../.." && pwd)"
LIST_APPS=("hypr" "waybar" "wofi" ".tmux" ".tmux.conf" ".zshenv" ".zshrc" "kitty" "btop")
DOWNLOAD_DIR="/tmp/downloads"
EXTRACT_DIR="/tmp/extracted_package"
FONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/IosevkaTerm.zip"
