wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpeaper/wp5596105-christianity-desktop-wallpapers.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = ~/Pictures/wallpeaper/uwp4946176.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = ~/Pictures/wallpeaper/john-3-16-wallpapers.jpg
    fit_mode = cover
}
